package com.sun.imageio.plugins.common;

import java.util.ArrayList;
import javax.imageio.ImageTypeSpecifier;
import javax.imageio.metadata.IIOMetadataFormatImpl;

public class StandardMetadataFormat extends IIOMetadataFormatImpl {
   private void addSingleAttributeElement(String var1, String var2, int var3) {
      this.addElement(var1, var2, 0);
      this.addAttribute(var1, "value", var3, true, (String)null);
   }

   public StandardMetadataFormat() {
      super("javax_imageio_1.0", 2);
      this.addElement("Chroma", "javax_imageio_1.0", 2);
      this.addElement("ColorSpaceType", "Chroma", 0);
      ArrayList var1 = new ArrayList();
      var1.add("XYZ");
      var1.add("Lab");
      var1.add("Luv");
      var1.add("YCbCr");
      var1.add("Yxy");
      var1.add("YCCK");
      var1.add("PhotoYCC");
      var1.add("RGB");
      var1.add("GRAY");
      var1.add("HSV");
      var1.add("HLS");
      var1.add("CMYK");
      var1.add("CMY");
      var1.add("2CLR");
      var1.add("3CLR");
      var1.add("4CLR");
      var1.add("5CLR");
      var1.add("6CLR");
      var1.add("7CLR");
      var1.add("8CLR");
      var1.add("9CLR");
      var1.add("ACLR");
      var1.add("BCLR");
      var1.add("CCLR");
      var1.add("DCLR");
      var1.add("ECLR");
      var1.add("FCLR");
      this.addAttribute("ColorSpaceType", "name", 0, true, (String)null, var1);
      this.addElement("NumChannels", "Chroma", 0);
      this.addAttribute("NumChannels", "value", 2, true, 0, Integer.MAX_VALUE);
      this.addElement("Gamma", "Chroma", 0);
      this.addAttribute("Gamma", "value", 3, true, (String)null);
      this.addElement("BlackIsZero", "Chroma", 0);
      this.addBooleanAttribute("BlackIsZero", "value", true, true);
      this.addElement("Palette", "Chroma", 0, Integer.MAX_VALUE);
      this.addElement("PaletteEntry", "Palette", 0);
      this.addAttribute("PaletteEntry", "index", 2, true, (String)null);
      this.addAttribute("PaletteEntry", "red", 2, true, (String)null);
      this.addAttribute("PaletteEntry", "green", 2, true, (String)null);
      this.addAttribute("PaletteEntry", "blue", 2, true, (String)null);
      this.addAttribute("PaletteEntry", "alpha", 2, false, "255");
      this.addElement("BackgroundIndex", "Chroma", 0);
      this.addAttribute("BackgroundIndex", "value", 2, true, (String)null);
      this.addElement("BackgroundColor", "Chroma", 0);
      this.addAttribute("BackgroundColor", "red", 2, true, (String)null);
      this.addAttribute("BackgroundColor", "green", 2, true, (String)null);
      this.addAttribute("BackgroundColor", "blue", 2, true, (String)null);
      this.addElement("Compression", "javax_imageio_1.0", 2);
      this.addSingleAttributeElement("CompressionTypeName", "Compression", 0);
      this.addElement("Lossless", "Compression", 0);
      this.addBooleanAttribute("Lossless", "value", true, true);
      this.addSingleAttributeElement("NumProgressiveScans", "Compression", 2);
      this.addSingleAttributeElement("BitRate", "Compression", 3);
      this.addElement("Data", "javax_imageio_1.0", 2);
      this.addElement("PlanarConfiguration", "Data", 0);
      var1 = new ArrayList();
      var1.add("PixelInterleaved");
      var1.add("PlaneInterleaved");
      var1.add("LineInterleaved");
      var1.add("TileInterleaved");
      this.addAttribute("PlanarConfiguration", "value", 0, true, (String)null, var1);
      this.addElement("SampleFormat", "Data", 0);
      var1 = new ArrayList();
      var1.add("SignedIntegral");
      var1.add("UnsignedIntegral");
      var1.add("Real");
      var1.add("Index");
      this.addAttribute("SampleFormat", "value", 0, true, (String)null, var1);
      this.addElement("BitsPerSample", "Data", 0);
      this.addAttribute("BitsPerSample", "value", 2, true, 1, Integer.MAX_VALUE);
      this.addElement("SignificantBitsPerSample", "Data", 0);
      this.addAttribute("SignificantBitsPerSample", "value", 2, true, 1, Integer.MAX_VALUE);
      this.addElement("SampleMSB", "Data", 0);
      this.addAttribute("SampleMSB", "value", 2, true, 1, Integer.MAX_VALUE);
      this.addElement("Dimension", "javax_imageio_1.0", 2);
      this.addSingleAttributeElement("PixelAspectRatio", "Dimension", 3);
      this.addElement("ImageOrientation", "Dimension", 0);
      var1 = new ArrayList();
      var1.add("Normal");
      var1.add("Rotate90");
      var1.add("Rotate180");
      var1.add("Rotate270");
      var1.add("FlipH");
      var1.add("FlipV");
      var1.add("FlipHRotate90");
      var1.add("FlipVRotate90");
      this.addAttribute("ImageOrientation", "value", 0, true, (String)null, var1);
      this.addSingleAttributeElement("HorizontalPixelSize", "Dimension", 3);
      this.addSingleAttributeElement("VerticalPixelSize", "Dimension", 3);
      this.addSingleAttributeElement("HorizontalPhysicalPixelSpacing", "Dimension", 3);
      this.addSingleAttributeElement("VerticalPhysicalPixelSpacing", "Dimension", 3);
      this.addSingleAttributeElement("HorizontalPosition", "Dimension", 3);
      this.addSingleAttributeElement("VerticalPosition", "Dimension", 3);
      this.addSingleAttributeElement("HorizontalPixelOffset", "Dimension", 2);
      this.addSingleAttributeElement("VerticalPixelOffset", "Dimension", 2);
      this.addSingleAttributeElement("HorizontalScreenSize", "Dimension", 2);
      this.addSingleAttributeElement("VerticalScreenSize", "Dimension", 2);
      this.addElement("Document", "javax_imageio_1.0", 2);
      this.addElement("FormatVersion", "Document", 0);
      this.addAttribute("FormatVersion", "value", 0, true, (String)null);
      this.addElement("SubimageInterpretation", "Document", 0);
      var1 = new ArrayList();
      var1.add("Standalone");
      var1.add("SinglePage");
      var1.add("FullResolution");
      var1.add("ReducedResolution");
      var1.add("PyramidLayer");
      var1.add("Preview");
      var1.add("VolumeSlice");
      var1.add("ObjectView");
      var1.add("Panorama");
      var1.add("AnimationFrame");
      var1.add("TransparencyMask");
      var1.add("CompositingLayer");
      var1.add("SpectralSlice");
      var1.add("Unknown");
      this.addAttribute("SubimageInterpretation", "value", 0, true, (String)null, var1);
      this.addElement("ImageCreationTime", "Document", 0);
      this.addAttribute("ImageCreationTime", "year", 2, true, (String)null);
      this.addAttribute("ImageCreationTime", "month", 2, true, (String)null, "1", "12", true, true);
      this.addAttribute("ImageCreationTime", "day", 2, true, (String)null, "1", "31", true, true);
      this.addAttribute("ImageCreationTime", "hour", 2, false, "0", "0", "23", true, true);
      this.addAttribute("ImageCreationTime", "minute", 2, false, "0", "0", "59", true, true);
      this.addAttribute("ImageCreationTime", "second", 2, false, "0", "0", "60", true, true);
      this.addElement("ImageModificationTime", "Document", 0);
      this.addAttribute("ImageModificationTime", "year", 2, true, (String)null);
      this.addAttribute("ImageModificationTime", "month", 2, true, (String)null, "1", "12", true, true);
      this.addAttribute("ImageModificationTime", "day", 2, true, (String)null, "1", "31", true, true);
      this.addAttribute("ImageModificationTime", "hour", 2, false, "0", "0", "23", true, true);
      this.addAttribute("ImageModificationTime", "minute", 2, false, "0", "0", "59", true, true);
      this.addAttribute("ImageModificationTime", "second", 2, false, "0", "0", "60", true, true);
      this.addElement("Text", "javax_imageio_1.0", 0, Integer.MAX_VALUE);
      this.addElement("TextEntry", "Text", 0);
      this.addAttribute("TextEntry", "keyword", 0, false, (String)null);
      this.addAttribute("TextEntry", "value", 0, true, (String)null);
      this.addAttribute("TextEntry", "language", 0, false, (String)null);
      this.addAttribute("TextEntry", "encoding", 0, false, (String)null);
      var1 = new ArrayList();
      var1.add("none");
      var1.add("lzw");
      var1.add("zip");
      var1.add("bzip");
      var1.add("other");
      this.addAttribute("TextEntry", "compression", 0, false, "none", var1);
      this.addElement("Transparency", "javax_imageio_1.0", 2);
      this.addElement("Alpha", "Transparency", 0);
      var1 = new ArrayList();
      var1.add("none");
      var1.add("premultiplied");
      var1.add("nonpremultiplied");
      this.addAttribute("Alpha", "value", 0, false, "none", var1);
      this.addSingleAttributeElement("TransparentIndex", "Transparency", 2);
      this.addElement("TransparentColor", "Transparency", 0);
      this.addAttribute("TransparentColor", "value", 2, true, 0, Integer.MAX_VALUE);
      this.addElement("TileTransparencies", "Transparency", 0, Integer.MAX_VALUE);
      this.addElement("TransparentTile", "TileTransparencies", 0);
      this.addAttribute("TransparentTile", "x", 2, true, (String)null);
      this.addAttribute("TransparentTile", "y", 2, true, (String)null);
      this.addElement("TileOpacities", "Transparency", 0, Integer.MAX_VALUE);
      this.addElement("OpaqueTile", "TileOpacities", 0);
      this.addAttribute("OpaqueTile", "x", 2, true, (String)null);
      this.addAttribute("OpaqueTile", "y", 2, true, (String)null);
   }

   public boolean canNodeAppear(String var1, ImageTypeSpecifier var2) {
      return true;
   }
}
